### PR TITLE
Removed duplicated paragraph

### PR DESCRIPTION
**Pull request by geoff-wasilwa**
The paragraph about escaping quotes is also mentioned under "Named attribute"

### CODE REVIEW

**Comment by mojavelinux** [comment]
Aha, I see what happened here. That example is supposed to explain when to do if the value contains a single quote. It's not otherwise mentioned what to do if you need to apply substitutions and the value has a single quote, so this is the right opportunity to do it. Could you update it accordingly?

Thanks for catching this!

**Comment by geoff-wasilwa** [comment]
@mojavelinux do I need to open a new PR?

**Comment by mojavelinux** [comment]
Nope, updating this one is just fine. I'll review.

**Comment by mojavelinux** [comment]
Technically what you had was correct, but it still wasn't illustrative. I came up with the following example instead:

```
title='A \'use case\' diagram, generated by https://plantuml.com[PlantUML]'
```

This combines the reason for needing to quote the attribute (the presence of the comma) with the reason for needing to enable substitutions (the precedence of the URL macro). And in this scenario, the single quotes need to be escaped around "use case".

**Pull request merged**
