### PR TITLE
Replace master document by main document

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm :100: in favor of the sentiment of this change, but I'm not sure "main" is the right word choice in this case. Let's try to pick an alternate word that is familiar in publishing. How about "principal", "primary", or "top-level"?

**Comment by Mogztter** [comment]
"primary" and "top-level" are fine.
In French, "main" and "principal" are somehow equivalent. The word "main" could be translated in French to "central" or "principal".
I might be wrong but in mind we can only have one "top-level" document and in this context that's not necessarily true. So "primary" feels more accurate.

**Comment by mojavelinux** [comment]
Let's try primary and see how it is received. (As usual, naming is hard ;))

**Comment by Mogztter** [comment]
I just noticed that we are already using "main document" in modules/directives/pages/include.adoc. For consistency, I will rename all occurrences.

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
