### PR TITLE
Move callout to the correct line and add indentation via xmllint

### PR DESCRIPTION
**Pull request by toraritte**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Can you remove the formatting. The purpose of the example is to show what the AsciiDoc converter produces, and it doesn't not indent the DocBook data.

**Comment by toraritte** [comment]
Just did. My output with `asciidoctor` 2.0.18 also added the lines

```
<?asciidoc-toc?>
<?asciidoc-numbered?>
```

but removed them as they also weren't in the original example. Is that ok?

**Comment by mojavelinux** [comment]
That's fine since they are not germane to this example. Thanks!

**Comment by toraritte** [comment]
Thanks a lot!

**Pull request merged**
